### ISSUE TITLE
Installation error on Ubuntu 16.04

### ISSUE THREAD

**Issue by Leva7** [railsware/upterm#1034]
I'm trying to build the project on Ubuntu 16.04 64-bit. I've cloned this repository and executed `sudo npm install` inside the folder.  
The installation took a while and then suddenly errors started appearing. [Here](https://pastebin.com/cV3v0utK) is the console output.  
Then the `npm install` finished and I ran `sudo npm run pack`. It also errored, [here](https://pastebin.com/sXwnXpUu) is its log.  

Is Ubuntu supported? As it seems from the errors, it has some trouble with the connection. However, my Internet is pretty stable, I can freely use the browser during the installation

**Comment by christianwico** [comment]
I've had the same errors.

It's kinda weird. If you try running `npm run electron`, Black Screen should start up. But whenever your try to build it with `npm run pack`, it gives that `icns2png` error. (It has something to do with an Electron Builder bug, or perhaps something wrong with the Linux configuration on the part of Black Screens devs.)

Don't know. And it's kinda inconvenient to start-up Black Screen via NPM every single time.

**Comment by christianwico** [comment]
@Leva7 , here's a quick fix if you don't mind using the Electron logo as Black Sceen's App Icon:

* Just **DELETE** the `build/icon.icns` file from the project folder.

This will force Electron Builder to use Electron's default icon which keeps it from having to invoke the `icns2png` component.

**Comment by Leva7** [comment]
@christianwico, but what about those ECONNRESET errors during `npm install`? I feel like that's the main cause of the problem. But I'll try your fix, maybe those errors can be ignored

**Comment by christianwico** [comment]
`ERRCONNRESET` kinda suggests a problem with your network connection. I get those problems whenever I'm at work because the network is behind a proxy. But at home, I never get those issues (except when the NPM Repository is having issues of some sort, which happens ever so often from where I reside.)

**Comment by Leva7** [comment]
@christianwico, the app did in fact start up when I ran `npm run electron`. Your fix also worked, allowing me to install the app. As for the network connection, maybe that's actually NPM's problem, because, as I've mentioned, my connection just fine and this problem persists on a different Ubuntu machine.

**Comment by LeoMartinDev** [comment]
Not working for me, Exit code: 127.
`/home/leo/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory`

**Comment by Leva7** [comment]
@vshatskyi Any ideas on how to get the icon functioning on Linux?

**Comment by vshatskyi** [comment]
Fixed. If you encounter a libreadline error, there are some workarounds here: https://github.com/electron-userland/electron-builder/issues/993

**Comment by Leva7** [comment]
No, the issue persists ([log](https://pastebin.com/mDCK69YD)). Is it perhaps because you've written 
```
"linux": {
  "icon": "icons"
}
```
while the icon files are named `icon.*`?

**Comment by vshatskyi** [comment]
The path is correct, it should be a directory name relative to `build/`.

**Comment by Leva7** [comment]
But there's no directory in `build/`. For me, there's just those three files:
- `icon.icns`
- `icon.png`
- `icon.ico`

**Comment by vshatskyi** [comment]
You might have forgotten to pull if you don't have this directory: https://github.com/railsware/upterm/tree/master/build/icons

**Comment by Leva7** [comment]
No, the reason why I didn't have the folder is that it's not in the latest release, as I got the source code from there

**Comment by Leva7** [comment]
But with the folder, the icon installs just fine
