### ISSUE TITLE
Sudo is impossible

### ISSUE THREAD

**Issue by ZackEyston** [railsware/upterm#1069]
I can't use the "sudo" command. The command tell me my password is always wrong, but in other shell all is well functioning. And I have the same problem with "su" command. Then, i have change my sudo config file to add "Defaults env_reset,pwfeedback" because i suppose that the problem. Finaly, i can see the asterix in place of my password. And when i type "alt gr" key, five asterix appear, so the bug is that fucking "alt gr" key. On the other side when I type "alt gr" whitout "sudo" or "su" command, everything works perfectly.

In the meantime, I will change my password. Oh, i have forget :+1: Good job for upterm, i want to use it everyday :) 

(Sorry for my english, i'm french, and the french people are so bad in english)

**Comment by vlad-shatskyi** [comment]
Can't reproduce. Can you try to open an editor (like nano or vim) in Upterm and type your password there? Is it displayed correctly?

**Comment by ZackEyston** [comment]
I have open vim with upterm in sample.test file, and when i press "alt-gr" in mey keyboard he wrote "AltGr" :/

**Comment by vlad-shatskyi** [comment]
@ZackEyston please install the latest master and try there. I fixed a relevant issue pretty recently.

**Comment by ZackEyston** [comment]
Okay, the bug is not fixed. 
However the AUR upterm version is 0.2.154-1 while the master is 0.2.155, so i have git clone and install it via npm command. I exec the 0.2.155 and the bug is still present.

**Comment by ZackEyston** [comment]
Thx, it work well in 0.2.157 :) :+1:
